services:
  wedding-invitation:
    build:
      context: .
      dockerfile: Containerfile
    container_name: wedding-invitation
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - public

networks:
  public:
    external: true
